name: ci

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    paths-ignore:
      - .github/**
      - README.md
      - LICENSE
      - .gitattributes
      - .gitignore

jobs:
  ci:
    name: Test with Node.JS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: true
          node-version-file: .node-version
      - name: Install dependencies
        run: npm install
      - name: Run CI tests
        run: npm run test:ci
  release:
    needs:
      - ci
    name: Run Release
    if: github.event_name == 'push'
    uses: thakyz/eslint-config-nekoboinick/.github/workflows/release.yml@main
    with:
      success: true
